services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    env_file: 
      - .env
    restart: always
    depends_on:
      - wordpress
    networks:
      - default

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file: 
      - .env
    restart: always
    depends_on:
      - mariadb
    networks:
      - default

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: 
     - .env
    restart: always
    networks:
      - default
    #command: mysqld --skip-grant-tables --user=root --datadir=/var/lib/mysql --socket=/run/mysqld/mysqld.sock --pid-file=/run/mysqld/mysqld.pid --console

networks:
  default: {}

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: /home/aklimchu/data/mariadb_data
      o: bind
      type: none
  wordpress_data:
    driver: local
    driver_opts:
      device: /home/aklimchu/data/wordpress_data
      o: bind
      type: none
