#CREATE DATABASE IF NOT EXISTS wordpress;

#CREATE USER 'wpuser'@'%' IDENTIFIED BY 'password';
#GRANT ALL PRIVILIGES ON *.* TO 'my_user'@'%' WITH GRANT OPTION;
#FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS wordpress;

#CREATE USER IF NOT EXISTS 'wpuser'@'%' IDENTIFIED BY 'password';
#GRANT ALL PRIVILEGES ON *.* TO 'wpuser'@'%' WITH GRANT OPTION;
#GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'password1234';

DROP USER IF EXISTS 'root'@'localhost';
DROP USER IF EXISTS 'root'@'%';
CREATE USER 'root'@'%' IDENTIFIED BY 'rootpass';
GRANT ALL PRIVILEGES ON wordpress.* TO 'root'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;