services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - 80:80 #should it be 430?
    volumes:
      - wordpress_data:/var/www/html
    #env_file: 
      #- .env
    environment:
      - NGINX_HOST=aklimchu.42.fr
      - NGINX_PORT=80
    restart: always
    depends_on:
      - wordpress
    networks:
      - src_default

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password1234
      WORDPRESS_DB_NAME: wordpress
    restart: always
        #env_file: 
      #- .env
    depends_on:
      - mariadb
    networks:
      - src_default

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - src_default

networks:
  src_default: {}

volumes:
  mariadb_data: {}
  wordpress_data: {}
