services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    #env_file: 
      #- .env
    environment:
      - NGINX_HOST=aklimchu.42.fr
    restart: always
    depends_on:
      - wordpress
    networks:
      - default

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password1234
      WORDPRESS_DB_NAME: wordpress
    restart: always
        #env_file: 
      #- .env
    depends_on:
      - mariadb
    networks:
      - default

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - default

networks:
  default: {}

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: /home/aklimchu/data/mariadb_data
      o: bind
      type: none
  wordpress_data:
    driver: local
    driver_opts:
      device: /home/aklimchu/data/wordpress_data
      o: bind
      type: none
